### ISSUE TITLE
Bug: SCA flow triggers `Cannot read property 'token' of null`

### ISSUE THREAD

**Issue by ericghpham** [square/ember-square-payment-form#51]
When the user fails the verification step in the SCA flow, it triggers an uncaught exception:

`
square-payment-form.js:720 Uncaught TypeError: Cannot read property 'token' of null
    at square-payment-form.js:720
    at paymentform:1
    at data.js:18
    at e.callback (data.js:23)
    at e.invoke (data.js:23)
    at e.handleChallenges (data.js:23)
    at e.messageReceived (data.js:18)
    at f (data.js:1)
    at r (lib.js:7)
`

This is caused because failing the verification step does not return a verification result, so the simple solution is to check for presence of the result.

**Comment by deanpapastrat** [comment]
Fixed by #52
